//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        public UserOrder()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public long orderId { get; set; }
        public System.DateTime orderDate { get; set; }
        public long orderBankCardPAN { get; set; }
        public string orderPostalAddress { get; set; }
        public decimal orderValue { get; set; }
        public long orderUserId { get; set; }
        public string orderDescription { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_UserOrder_OrderBankCardPAN
        /// </summary>
        public virtual BankCard BankCard { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_OrderLine_LineOrderId
        /// </summary>
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_UserOrder_OrderUserId
        /// </summary>
        public virtual UserProfile UserProfile { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + orderDate.GetHashCode();
    			hash = hash * multiplier + orderBankCardPAN.GetHashCode();
    			hash = hash * multiplier + (orderPostalAddress == null ? 0 : orderPostalAddress.GetHashCode());
    			hash = hash * multiplier + orderValue.GetHashCode();
    			hash = hash * multiplier + orderUserId.GetHashCode();
    			hash = hash * multiplier + (orderDescription == null ? 0 : orderDescription.GetHashCode());
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type?
    	    
            UserOrder target = obj as UserOrder;
    
    		return true
               &&  (this.orderId == target.orderId )       
               &&  (this.orderDate == target.orderDate )       
               &&  (this.orderBankCardPAN == target.orderBankCardPAN )       
               &&  (this.orderPostalAddress == target.orderPostalAddress )       
               &&  (this.orderValue == target.orderValue )       
               &&  (this.orderUserId == target.orderUserId )       
               &&  (this.orderDescription == target.orderDescription )       
               ;
    
        }
    
    
    	public static bool operator ==(UserOrder  objA, UserOrder  objB)
        {
            // Check if the objets are the same UserOrder entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(UserOrder  objA, UserOrder  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strUserOrder = new StringBuilder();
    
    		strUserOrder.Append("[ ");
           strUserOrder.Append(" orderId = " + orderId + " | " );       
           strUserOrder.Append(" orderDate = " + orderDate + " | " );       
           strUserOrder.Append(" orderBankCardPAN = " + orderBankCardPAN + " | " );       
           strUserOrder.Append(" orderPostalAddress = " + orderPostalAddress + " | " );       
           strUserOrder.Append(" orderValue = " + orderValue + " | " );       
           strUserOrder.Append(" orderUserId = " + orderUserId + " | " );       
           strUserOrder.Append(" orderDescription = " + orderDescription + " | " );       
            strUserOrder.Append("] ");    
    
    		return strUserOrder.ToString();
        }
    
    
    }
}
